[project]
name = "smolagents-code-tester"
version = "0.1.0"
description = "A smolagents project for testing code in an isoalted workspace"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "daytona-sdk==0.10.2",
    "python-dotenv>=1.0.1",
    "smolagents>=1.8.0",
]
